/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tr_com_turkcellteknoloji_demo_ndk_ExponentialWrapper */

#ifndef _Included_tr_com_turkcellteknoloji_demo_ndk_ExponentialWrapper
#define _Included_tr_com_turkcellteknoloji_demo_ndk_ExponentialWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tr_com_turkcellteknoloji_demo_ndk_ExponentialWrapper
 * Method:    exponential
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_tr_com_turkcellteknoloji_demo_ndk_ExponentialWrapper_exponential
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
